{% set name = "f2c" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
   git_url: https://github.com/fermi-lat/f2c.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
